[2024-12-15T10:07:16.174+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T10:07:16.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-15T09:47:11.600911+00:00 [queued]>
[2024-12-15T10:07:16.185+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-15T09:47:11.600911+00:00 [queued]>
[2024-12-15T10:07:16.185+0000] {taskinstance.py:2866} INFO - Starting attempt 5 of 6
[2024-12-15T10:07:16.189+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Run_bash_to_python_file> on 2024-12-15 09:47:11.600911+00:00
[2024-12-15T10:07:16.193+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4712) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T10:07:16.193+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK_DEPN_3', 'Run_bash_to_python_file', 'manual__2024-12-15T09:47:11.600911+00:00', '--job-id', '1829', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK_DEPN_3.py', '--cfg-path', '/tmp/tmp0yv6h62r']
[2024-12-15T10:07:16.195+0000] {standard_task_runner.py:105} INFO - Job 1829: Subtask Run_bash_to_python_file
[2024-12-15T10:07:16.195+0000] {standard_task_runner.py:72} INFO - Started process 4714 to run task
[2024-12-15T10:07:16.211+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-15T09:47:11.600911+00:00 [running]> on host 6418ebfba5fb
[2024-12-15T10:07:16.237+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK_DEPN_3' AIRFLOW_CTX_TASK_ID='Run_bash_to_python_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T09:47:11.600911+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T09:47:11.600911+00:00'
[2024-12-15T10:07:16.237+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T10:07:16.242+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK_DEPN_3.py", line 20, in get_param
    controller = context["dag_run"].conf['message']
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
[2024-12-15T10:07:16.246+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=PRCS_TEST_FRAMEWORK_DEPN_3, task_id=Run_bash_to_python_file, run_id=manual__2024-12-15T09:47:11.600911+00:00, execution_date=20241215T094711, start_date=20241215T100716, end_date=20241215T100716
[2024-12-15T10:07:16.252+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T10:07:16.252+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1829 for task Run_bash_to_python_file ('message'; 4714)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK_DEPN_3.py", line 20, in get_param
    controller = context["dag_run"].conf['message']
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
[2024-12-15T10:07:16.294+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T10:07:16.303+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T10:07:16.303+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
