[2024-12-16T16:42:47.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T16:42:47.824+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-16T16:19:06.066755+00:00 [queued]>
[2024-12-16T16:42:47.836+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-16T16:19:06.066755+00:00 [queued]>
[2024-12-16T16:42:47.837+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 6
[2024-12-16T16:42:47.854+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Run_bash_to_python_file> on 2024-12-16 16:19:06.066755+00:00
[2024-12-16T16:42:47.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK_DEPN_3', 'Run_bash_to_python_file', 'manual__2024-12-16T16:19:06.066755+00:00', '--job-id', '1961', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK_DEPN_3.py', '--cfg-path', '/tmp/tmpa_j0z7co']
[2024-12-16T16:42:47.858+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-16T16:42:47.863+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2024-12-16T16:42:47.861+0000] {standard_task_runner.py:105} INFO - Job 1961: Subtask Run_bash_to_python_file
[2024-12-16T16:42:48.007+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_3.Run_bash_to_python_file manual__2024-12-16T16:19:06.066755+00:00 [running]> on host 3b6d26b512f1
[2024-12-16T16:42:48.108+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK_DEPN_3' AIRFLOW_CTX_TASK_ID='Run_bash_to_python_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T16:19:06.066755+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T16:19:06.066755+00:00'
[2024-12-16T16:42:48.112+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T16:42:48.125+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-16T16:42:48.129+0000] {process_utils.py:132} INFO - Sending 15 to group 204. PIDs of all processes in the group: [204]
[2024-12-16T16:42:48.132+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 204
[2024-12-16T16:42:48.135+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-16T16:42:48.151+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 402, in wrapper
    from airflow.decorators.base import DecoratedOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/__init__.py", line 30, in <module>
    from airflow.decorators.sensor import sensor_task
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/sensor.py", line 23, in <module>
    from airflow.sensors.python import PythonSensor
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/python.py", line 30, in <module>
    class PythonSensor(BaseSensorOperator):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 534, in __new__
    new_cls.__init__ = cls._apply_defaults(new_cls.__init__)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 439, in _apply_defaults
    sig_cache = inspect.signature(func)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3341, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3081, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 2545, in _signature_from_callable
    pass
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-16T16:42:48.159+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=PRCS_TEST_FRAMEWORK_DEPN_3, task_id=Run_bash_to_python_file, run_id=manual__2024-12-16T16:19:06.066755+00:00, execution_date=20241216T161906, start_date=20241216T164247, end_date=20241216T164248
[2024-12-16T16:42:48.176+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T16:42:48.192+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=204, status='terminated', exitcode=2, started='16:42:47') (204) terminated with exit code 2
[2024-12-16T16:42:48.193+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-12-16T16:42:48.211+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
