[2024-12-15T14:07:27.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T14:07:27.567+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:22:37.379874+00:00 [queued]>
[2024-12-15T14:07:27.569+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:22:37.379874+00:00 [queued]>
[2024-12-15T14:07:27.570+0000] {taskinstance.py:2866} INFO - Starting attempt 14 of 18
[2024-12-15T14:07:27.574+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ExecuteNotebook> on 2024-12-15 13:22:37.379874+00:00
[2024-12-15T14:07:27.577+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=826) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T14:07:27.578+0000] {standard_task_runner.py:72} INFO - Started process 838 to run task
[2024-12-15T14:07:27.577+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK1', 'ExecuteNotebook', 'manual__2024-12-15T13:22:37.379874+00:00', '--job-id', '1917', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK1.py', '--cfg-path', '/tmp/tmpn8rso5yp']
[2024-12-15T14:07:27.578+0000] {standard_task_runner.py:105} INFO - Job 1917: Subtask ExecuteNotebook
[2024-12-15T14:07:27.592+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK1.ExecuteNotebook manual__2024-12-15T13:22:37.379874+00:00 [running]> on host e12d581ca20f
[2024-12-15T14:07:27.615+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK1' AIRFLOW_CTX_TASK_ID='ExecuteNotebook' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T13:22:37.379874+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T13:22:37.379874+00:00'
[2024-12-15T14:07:27.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T14:07:27.622+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T14:07:36.271+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-15T14:07:36.277+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK1.py", line 71, in execute_notebook
    subprocess.run(command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '
                docker exec aa0e1735289c jupyter nbconvert --to notebook --execute                 --output /home/iceberg/notebooks/Log_output/PRCS_TEST_FRAMEWORK1/test1_executed.ipynb                 /home/iceberg/notebooks/notebooks/staging/uat/airflow/test1.ipynb
            ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK1.py", line 76, in execute_notebook
    raise Exception(f"failed as {e.stderr or e.output} notebook path: ")
Exception: failed as None notebook path: 
[2024-12-15T14:07:36.284+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=PRCS_TEST_FRAMEWORK1, task_id=ExecuteNotebook, run_id=manual__2024-12-15T13:22:37.379874+00:00, execution_date=20241215T132237, start_date=20241215T140727, end_date=20241215T140736
[2024-12-15T14:07:36.289+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T14:07:36.289+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1917 for task ExecuteNotebook (failed as None notebook path: ; 838)
Traceback (most recent call last):
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK1.py", line 71, in execute_notebook
    subprocess.run(command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '
                docker exec aa0e1735289c jupyter nbconvert --to notebook --execute                 --output /home/iceberg/notebooks/Log_output/PRCS_TEST_FRAMEWORK1/test1_executed.ipynb                 /home/iceberg/notebooks/notebooks/staging/uat/airflow/test1.ipynb
            ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script/PRCS_TEST_FRAMEWORK1.py", line 76, in execute_notebook
    raise Exception(f"failed as {e.stderr or e.output} notebook path: ")
Exception: failed as None notebook path: 
[2024-12-15T14:07:36.297+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T14:07:36.305+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T14:07:36.306+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
